//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project1.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int Id { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
        public Nullable<System.DateTime> DateBirth { get; set; }
        public string Snils { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public Nullable<int> IdPolicy { get; set; }
        public Nullable<int> IdPassport { get; set; }
    
        public virtual Passports Passports { get; set; }
        public virtual Policies Policies { get; set; }
    }
}
